name: "Workflow : Push"

on:
  push:
    branches:
      - master
  workflow_dispatch:  # workflow_dispatch 호출

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Opentelemetry Instrumentation
        run: |
          mkdir -p src/main/jib/otel
          curl -o 'src/main/jib/otel/opentelemetry-javaagent.jar' -L 'https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.29.0/opentelemetry-javaagent.jar'

      - name: Build with Jib
        run: |
          ./gradlew jib
      
      - name: Notify Deployment
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '`backend-server` deployed with version `${{ github.sha }}`'
